### ISSUE TITLE
Feature request: template inheritance

### ISSUE THREAD

**Issue by Darxor** [zipreport/zipreport#32]
Hey! I'm currently working on incorporating `zipreport` into my workflow for report generation and one feature in particular would be very helpful to me

I have a lot of different templates that reuse many of the same elements, like a core jinja template, that houses pagejs, universal color settings, etc. Ideally I would like to separate them out to a directory like so:

```
├── globals
│   ├── base.html
│   ├── base.css
│   ├── paged.js
│   ├── ...
├── template01
│   ├── index.html
│   ├── manifest.json
│   ├── ...
├── template02
│   ├── index.html
│   ├── manifest.json
│   ├── ...
```

Where `template01/index.html` extends `globals/base.html`.

I understand that I can't do something like `{% extends "../globals/base.html" %}`, because of how template's directory is isolated into ZipFS.

In a script that builds the actual report I could just add a dependency to manifest and copy over required folders inside my own `ReportFileLoader`.  But this approach means that I won't be able to use `zipreport debug` anymore.

Are you considering some kind of template inheritance for zipreport?

**Comment by joao-pinheiro** [comment]
Hi Darxor, thank you for your interest in the project. 

Currently, there is no plan to add cascading/inheritance templates, and such functionality should probably reside in the tooling (eg. zipreport-cli) and not on the library itself, as having a single template per file is actually one of the goals of the library (opposed to a multi-template file). 

However, the specific issue you have can easily be solved by using symbolic links, and adding optional symbolic link support is quite easy - in your case, you would symlink globals into the different templates, and the build process would follow the symlinks. Would this approach solve your problem?

**Comment by Darxor** [comment]
Yeah, I think symlinks can actually work. I am a bit uncomfortable setting them up permanently, since afaik git doesn't play nice with symlinked directories.

But creating a symlink on the fly could work, and I can make a shim for that on my end. Only possible downside I see is if my templates are in a read-only directory.

So yeah, thanks for the idea, I think I can manage with that :) Still would appreciate if some sort of external dependency collection would make it into the tooling or the library.

**Comment by joao-pinheiro** [comment]
I need to add explicit support for symlinks still :) since by default they are ignored. Im preparing a new version minor with this change

**Comment by joao-pinheiro** [comment]
@Darxor please test 2.1.0 version, you can use symlinks within templates by using the '-s' flag in zipreport build/zipreport debug. If you find any additional issues please let me know.

**Comment by Darxor** [comment]
Thanks for your quick responses and changes! Worked like a charm, both as a flag and as an argument to`ReportFileLoader.load_dir()`.

I am moving a complex report template I once made with rmarkdown/pagedown to zipreport and having some ideas for improvement. Gonna be posting some of them to issues, if you don't mind :)
