### ISSUE TITLE
Feature: Bundled custom jinja filters and tests

### ISSUE THREAD

**Issue by Darxor** [zipreport/zipreport#34]
Would be nice to have an option to provide custom filters and tests to templates (see [docs](https://jinja.palletsprojects.com/en/3.0.x/api/?highlight=filters#custom-filters)) and better yet to bundle them with report and be able to use them even with `zipreport debug`.

Right now I don't see a way to provide filters/tests other than subclassing `zipreport.template.JinjaRender` and overriding `get_env()`, which is not what I can do with a wrapper around cli tool, or updating `jinja2.filters.FILTERS`/`jinja2.tests.TESTS` by reference, which seems hacky to me.

I've seen docs mentioning way to provide filters through `jinja_options`, but I don't see how that can work given that `jinja2.Environment` does not accept filters on init and requires to change `Environment.filters` afterwards. This also will not work for `zipreport debug`, which is an important flaw IMO.

Ideally I would like to put filters into a file like `filters.py`, tests to `tests.py`, maybe reference them in the manifest. Have them loaded with `importlib` & `inspect` and added to jinja's `Environment.filters` before report compilation. Additionally, it would be nice to provide jinja extensions to `zipreport debug` somehow, maybe mention them in manifest too.

Proposed approach opens up a way for ACE, but I don't think running untrusted templates is a good idea anyway. Maybe this could also help with issues preventing dynamic image loading.

**Comment by joao-pinheiro** [comment]
You can easily register your own filters by registering them in the dict jinja2.defaults.DEFAULT_FILTERS, which is the global filter registry. This is the way zipreport registers its own image rendering filters.

I don't really see any advantage on using environments, as filters are often application-specific and the templates are (or should be) trusted "code". Environment filters in jinja2 start by being  a deepcopy of DEFAULT_FILTERS, so any system-wide filters will be available to your specific template. I think the most common usage scenario for environments is to provide module-specific functionality within a global web template, not when you''re creating on demand rendering contexts. Obviously my stance comes from my use cases, so yours may be different :) Can you please give me a bit more context on your specific use case? I can evaluate adding optional environment support to the rendering pipeline.

One thing to note is that there is nothing python-specific within the pdf generation engine. You can easily run python code inside a template if you really want (last case scenario, a filter function can run arbitrary python code), but that is often frowned upon, even in python :)

**Comment by Darxor** [comment]
My usecase is stateless FastAPI that serves different reports on demand: it accepts a template name and corresponding report data, then prints that specific parametrized report. I have not yet dabbled with async calls to zipreport, but relying on jinja2 global default will surely force me to separate zipreport to a different process, or otherwise I will have cross-contamination of filters.

> You can easily register your own filters by registering them in the dict jinja2.defaults.DEFAULT_FILTERS, which is the global filter registry. This is the way zipreport registers its own image rendering filters.

My biggest problem with this is I don't really see a clean way to use filters with "zipreport debug", without subclassing original code and having to rely on implementation details since I have to keep the same python interpreter running.

**Comment by joao-pinheiro** [comment]
> My usecase is stateless FastAPI that serves different reports on demand: it accepts a template name and corresponding report data, then prints that specific parametrized report. I have not yet dabbled with async calls to zipreport (...)

zipreport is not thread-safe, but if you are instancing per call this shouldn't be a problem. But I get your problem, you want a way to pack filters with the templates, so you can use them "on-demand".

> My biggest problem with this is I don't really see a clean way to use filters with "zipreport debug", without subclassing original code and having to rely on implementation details since I have to keep the same python interpreter running.

true, and you are right, it is an oversight. Let me ponder possible solutions and get back to you :)

**Comment by joao-pinheiro** [comment]
Hi,

Just built a new zipreport version, 2.2.0, that implements support for a custom wrapper class for Jinja2 Environment(). It allows for complete customization of the Environment object before rendering a report. The documentation isn't updated yet, but please have a look at the following examples:

https://github.com/zipreport/zipreport/blob/master/examples/code/custom_filter_example/main.py
https://github.com/zipreport/zipreport/tree/master/examples/reports/env_wrapper

They also include a *zipreport debug* example using a custom wrapper file. Please let me know of any problems you may find, and if this alleviates some of the mentioned problems.

**Comment by joao-pinheiro** [comment]
Closing issue, if further help required on this topic, please create a new issue :)
